### ISSUE TITLE
Getting some errors

### ISSUE THREAD

**Issue by rachellyne** [intermine/go-intermod#1]
Searching with a small list of human genes and viewing the enrichment:

Yeast, mouse and fish:
Error loading results. The server says: "Bad parameters. I expected a value for each of [correction, list, maxp, widget] but I didn't get any values for [list]"

**Comment by yochannah** [comment]
Most of the mines don't yet run the web service needed for enrichment - they'll need https://github.com/intermine/intermine/releases/tag/intermine-1.6.6 for it to work. I've added a slightly more informative message suggesting this fact, and I'll close this issue for now. 

Beta flymine also doesn't return results, but that's because of this: https://github.com/intermine/intermine/issues/1364
